### PR TITLE
Fix per channel speed due to outdated querySelector

### PR DESCRIPTION
**Pull request by neon-dev**

### CODE REVIEW

**Comment by andrewbrey** [comment]
@neon-dev Thank you very much for your contribution here! Frankly, I'm amazed that one of the 13 Firefox installs (everyone who isn't me) has enough interest to bother making an update, so thank you!

There are still a couple things that I think need to prevent me from merging this right away though:

1. This change removes the behavior of coalescing the `channel name` instead only trying one selector. This behavior was put in place because I learned from experience that YouTube does A-B testing (or perhaps gradual change rollout/something similar) of the html structure and so there may still be times where one of the "old" selectors is the correct one depending on who loads the page and when/from where.
2. Unfortunately, I've allowed this code and more importantly the tooling to build it get old enough that it is no longer compatible with the versions of node/npm I have on my system, which means I can't actually build the project. In #7 I've addressed this by introducing a dockerized environment, but it would be more work than I think is worth it to bring these updates into `master` without bringing some of the other improvements also.

I think for the immediate term, my plan will be to do a halfway measure where I add _only_ a dockerfile and not some of the other containerization ecosystem I put into #7, which will allow me to incorporate your change here and do a build and ship a patched version to the Firefox store. Phwew, this is all probably more than needed to be explained, but there we have it.

I am going to leave your PR here open and unmerged for right now and I'm going to try and get to this half-measure this weekend. Again, thank you for your contribution!

**Comment by neon-dev** [comment]
Hey @andrewbrey. Thanks, no big deal.
I didn't think about the A-B testing so I just thought the `||` was for channel vs. video pages. On the other hand, these query selectors were very old now so Youtube won't use them anywhere anymore. If you know of some recently used alternative selectors, I'll gladly add them.

Hopefully this PR doesn't cause too much work, since you have a whole rework in the pipeline.
Thank you again for updating this old code base, so there's a fix available until your new version is ready :)

**Comment by andrewbrey** [comment]
@neon-dev I don't know off hand if the old selectors can be omitted, but my gut guess is that yes they probably can - I only brought that up as something I wasn't 100% sure about in the change you made and I would need to do some tinkering to get a better sense of the redundancy of the old selectors and the need to coalesce the lookup. That said, it all becomes redundant with the rework that's coming so probably not worth laboring over!

I don't think it'll be toooo much work to get a build working on my machine again, just a bit of docker stuff which will be easy enough, I just don't have time to look at it till the weekend. I'll do my best to get an interim-fix out there for Firefox though so that you aren't held up waiting on the larger refactor.

Cheers!

**Comment by andrewbrey** [comment]
@neon-dev Thank you very much for taking a look at this for me - as the git graph is already somewhat confusing right now in feature branches due to the rewrite I am doing, I went ahead and implemented a fix for this independently ( see 85d1412 ) and am going to close this PR without merging the changes you made. It turned out that there was a bit more that needed to happen than the changes you made, so I think this is the easier path forward. Seriously, thank you a lot for helping on the project and next time hopefully external contributions will be a bit easier to merge straight up!

Incidentally, the updated extension has been deployed to the firefox addon store, so look for version `1.4.10` out there which should work correctly again - let me know if not!

**Comment by neon-dev** [comment]
@andrewbrey thanks so much. Yeah it works now, but I found another few issues with it:
1. It did for some reason copy the channel speed over to the video speed ~~and now I can't unset it for the specific video.~~ Ok I found out you can unset it via the dedicated options page. Small suggestion: Setting speed to 0 could unset it (or add a button, but it's not necessary).
2. If you manually override the speed from the youtube player, it resets to the addon's speed ~~after a few seconds.~~ when you click on the addon's icon to open the popup menu. Same when you pause, then unpause the video.

**Comment by andrewbrey** [comment]
@neon-dev both of these "work as designed" for this version of the codebase - this is to say, these are both byproducts of the way I originally implemented the speed change logic. Both of these items already have an issue related to them within the "Refactor" project and will be made to work more intuitively in the rewrite. Don't hold your breath on a real fix for either of these within this version as it would not be worth the effort when I'm already addressing them in the rewrite.

A couple additional notes/thoughts - regarding (1) you are right, the best workaround to "unsetting" a speed is just to delete it from the options page (which is less than ideal especially with as minimal as the options page is for now), but it is a viable workaround.

Regarding (2), my intention with the rewrite is to make the native speed control and the extension play nicer together by listening to the speed change events emitted by the video but as of yet I haven't decided whether using the native controls will create a "memory" entry for the video or simply temporarily disable the extension for this video...still debating, but for now, treat the extension as the source of truth for your video speed and don't bother setting speed (even as 1-off operations) through the native YouTube controls.

**Comment by neon-dev** [comment]
No worries, neither of those are a big deal and I certainly wouldn't expect a fix on the old code base.
Regarding your thoughts, I don't know anything about the possibilities and limitations when writing addons, but a general rule of thumb would be to only act once per navigation or refresh event. So set the speed initially and don't worry about what happens afterwards. If the user decides to change the speed via the video menu, it's intentional. Another small issue is that the speed set by the addon is not reflected in the video menu but I can see why that is.
Edit: 2) also causes another issue because even on videos where nothing is set in the addon, it reverts the playback speed to 1x when pausing

**Pull request closed without merging**
